version: "3.7"
services:
  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
